// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutBacktop: typeof import('@nutui/nutui-taro')['Backtop']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutOverlay: typeof import('@nutui/nutui-taro')['Overlay']
    NutPrice: typeof import('@nutui/nutui-taro')['Price']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
  }
}
